# Generated by Django 4.2.9 on 2026-06-29 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_debug', '0006_project_apigroup_project_apiinterface_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='任务ID')),
                ('task_type', models.CharField(choices=[('plan', '规划任务')], default='plan', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '完成'), ('failed', '失败'), ('timeout', '超时')], default='pending', max_length=20, verbose_name='执行状态')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.CharField(blank=True, default='', max_length=100, verbose_name='当前步骤')),
                ('step_results', models.JSONField(blank=True, default=dict, verbose_name='步骤结果')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='最终结果')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='api_debug.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'Agent任务',
                'verbose_name_plural': 'Agent任务',
                'db_table': 'api_debug_agent_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
