# Generated by Django 4.2.9 on 2026-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentinterfacefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '完成'), ('failed', '失败'), ('timeout', '超时'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
    ]
