# Generated by Django 4.2.9 on 2026-06-17 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_debug.apigroup', verbose_name='父分组')),
            ],
            options={
                'verbose_name': '接口分组',
                'verbose_name_plural': '接口分组',
                'db_table': 'api_debug_group',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApiInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('websocket', 'WebSocket'), ('rpc', 'RPC')], default='http', max_length=20, verbose_name='协议类型')),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.CharField(max_length=2048, verbose_name='请求地址')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='查询参数')),
                ('body_type', models.CharField(blank=True, choices=[('json', 'JSON'), ('form', 'Form'), ('xml', 'XML'), ('raw', 'Raw'), ('none', 'None')], default='none', max_length=20, verbose_name='请求体类型')),
                ('body', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('ws_message', models.TextField(blank=True, default='', verbose_name='WebSocket消息')),
                ('rpc_method', models.CharField(blank=True, default='', max_length=200, verbose_name='RPC方法名')),
                ('rpc_service', models.CharField(blank=True, default='', max_length=200, verbose_name='RPC服务名')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_interfaces', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='api_debug.apigroup', verbose_name='分组')),
            ],
            options={
                'verbose_name': 'API接口',
                'verbose_name_plural': 'API接口',
                'db_table': 'api_debug_interface',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DebugResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('websocket', 'WebSocket'), ('rpc', 'RPC')], max_length=20, verbose_name='协议类型')),
                ('request_url', models.CharField(max_length=2048, verbose_name='请求地址')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('request_headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP状态码')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='响应体')),
                ('elapsed_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], max_length=20, verbose_name='执行状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_results', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debug_results', to='api_debug.apiinterface', verbose_name='关联接口')),
            ],
            options={
                'verbose_name': '调试结果',
                'verbose_name_plural': '调试结果',
                'db_table': 'api_debug_result',
                'ordering': ['-id'],
            },
        ),
    ]
