# Generated by Django 4.2.9 on 2026-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_debug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinterface',
            name='assertions',
            field=models.JSONField(blank=True, default=list, verbose_name='断言规则'),
        ),
    ]
