# Generated by Django 4.2.9 on 2026-06-23 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_debug', '0002_apiinterface_assertions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='链路名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('nodes', models.JSONField(blank=True, default=list, verbose_name='节点列表')),
                ('edges', models.JSONField(blank=True, default=list, verbose_name='连线列表')),
                ('globals', models.JSONField(blank=True, default=list, verbose_name='全局参数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '链路测试',
                'verbose_name_plural': '链路测试',
                'db_table': 'api_debug_chain',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChainResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '完成'), ('failed', '失败'), ('timeout', '超时')], default='running', max_length=20, verbose_name='执行状态')),
                ('step_results', models.JSONField(blank=True, default=list, verbose_name='步骤结果')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='api_debug.chain', verbose_name='关联链路')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_results', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '链路结果',
                'verbose_name_plural': '链路结果',
                'db_table': 'api_debug_chain_result',
                'ordering': ['-id'],
            },
        ),
    ]
