# Generated by Django 4.2.9 on 2026-06-26 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_debug', '0003_chain_chainresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('variables', models.JSONField(blank=True, default=list, help_text='键值对列表，如 [{"key": "base_url", "value": "http://..."}]', verbose_name='环境变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '环境变量',
                'verbose_name_plural': '环境变量',
                'db_table': 'api_debug_environment',
                'ordering': ['-id'],
            },
        ),
    ]
