# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_debug', '0004_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='base_url',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='HTTP基础地址'),
        ),
        migrations.AddField(
            model_name='environment',
            name='ws_base_url',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='WebSocket基础地址'),
        ),
        migrations.AddField(
            model_name='environment',
            name='rpc_base_url',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='RPC基础地址'),
        ),
        migrations.AddField(
            model_name='environment',
            name='auth_type',
            field=models.CharField(
                choices=[
                    ('none', '无认证'),
                    ('bearer', 'Bearer Token'),
                    ('api_key', 'API Key'),
                    ('basic', 'Basic Auth'),
                    ('custom', '自定义 Header'),
                ],
                default='none',
                max_length=20,
                verbose_name='认证类型',
            ),
        ),
        migrations.AddField(
            model_name='environment',
            name='auth_header',
            field=models.CharField(blank=True, default='Authorization', max_length=100, verbose_name='认证Header名'),
        ),
        migrations.AddField(
            model_name='environment',
            name='auth_token',
            field=models.TextField(blank=True, default='', verbose_name='认证Token/值'),
        ),
        migrations.AddField(
            model_name='environment',
            name='auth_username',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Basic用户名'),
        ),
        migrations.AddField(
            model_name='environment',
            name='auth_password',
            field=models.TextField(blank=True, default='', verbose_name='Basic密码'),
        ),
    ]
