# Generated by Django 4.2.9 on 2026-06-29 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_existing_data_to_projects(apps, schema_editor):
    Project = apps.get_model('api_debug', 'Project')
    ProjectMember = apps.get_model('api_debug', 'ProjectMember')
    ApiGroup = apps.get_model('api_debug', 'ApiGroup')
    ApiInterface = apps.get_model('api_debug', 'ApiInterface')
    Environment = apps.get_model('api_debug', 'Environment')
    Chain = apps.get_model('api_debug', 'Chain')
    DebugResult = apps.get_model('api_debug', 'DebugResult')
    ChainResult = apps.get_model('api_debug', 'ChainResult')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])

    user_ids = set()
    for model in (ApiGroup, ApiInterface, Environment, Chain, DebugResult, ChainResult):
        user_ids.update(model.objects.exclude(created_by_id=None).values_list('created_by_id', flat=True))

    for user in User.objects.filter(id__in=user_ids):
        membership = ProjectMember.objects.filter(user=user).select_related('project').order_by('id').first()
        if membership:
            project = membership.project
        else:
            project = Project.objects.create(
                name='默认项目',
                description='迁移已有个人数据时自动创建的项目',
                created_by=user,
            )
            ProjectMember.objects.get_or_create(project=project, user=user, defaults={'role': 'owner'})
        ApiGroup.objects.filter(created_by=user, project__isnull=True).update(project=project)
        ApiInterface.objects.filter(created_by=user, project__isnull=True).update(project=project)
        Environment.objects.filter(created_by=user, project__isnull=True).update(project=project)
        Chain.objects.filter(created_by=user, project__isnull=True).update(project=project)
        DebugResult.objects.filter(created_by=user, project__isnull=True).update(project=project)
        ChainResult.objects.filter(created_by=user, project__isnull=True).update(project=project)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_debug', '0005_environment_runtime_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'api_debug_project',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='apigroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_groups', to='api_debug.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='apiinterface',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_interfaces', to='api_debug.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='chain',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='api_debug.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='chainresult',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_results', to='api_debug.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='debugresult',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debug_results', to='api_debug.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='api_debug.project', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api_debug.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'db_table': 'api_debug_project_member',
                'ordering': ['project_id', 'id'],
                'unique_together': {('project', 'user')},
            },
        ),
   
        migrations.RunPython(migrate_existing_data_to_projects, noop_reverse),
    ]
