"""
300 接口规模匹配准确率测试数据集
5 行业 × 60 接口 ≈ 300，用例 ≈ 500+
"""
from apps.agent.services.indexing.interface_indexer import tokenize

def _p(iid, name, method='GET', url='', group='', desc='',
        req=None, resp=None):
    path = url.split('?')[0].split('{')[0].rstrip('/') if url else ''
    parts = [name or '', method or '', url or '', path, group or '', desc or '']
    if req: parts.extend(req)
    if resp: parts.extend(resp)
    return {
        'interface_id': iid, 'name': name, 'method': method,
        'protocol': 'http', 'url': url, 'path': path,
        'group': group, 'description': desc,
        'request_fields': req or [], 'response_fields': resp or [],
        'tokens': sorted(tokenize(' '.join(parts))),
    }

# ═══════════════════════════════════════════════════════════════
#  电商行业 60 接口
# ═══════════════════════════════════════════════════════════════
ECOMMERCE = [
    # 用户模块 (10)
    _p(1, '用户注册', 'POST', '/api/users/register', '用户', '用户注册账号',
       ['username', 'password', 'phone', 'email', 'verify_code'], ['user_id', 'status']),
    _p(2, '用户登录', 'POST', '/api/users/login', '用户', '用户登录获取token',
       ['username', 'password'], ['access_token', 'refresh_token', 'user_id']),
    _p(3, '用户登出', 'POST', '/api/users/logout', '用户', '用户退出登录',
       ['refresh_token'], []),
    _p(4, '修改密码', 'POST', '/api/users/change-password', '用户', '修改用户密码',
       ['old_password', 'new_password'], []),
    _p(5, '个人信息查询', 'GET', '/api/users/profile', '用户', '查询当前用户个人信息',
       [], ['user_id', 'username', 'phone', 'email', 'avatar', 'nickname']),
    _p(6, '修改个人信息', 'PUT', '/api/users/profile', '用户', '修改用户个人资料',
       ['nickname', 'avatar', 'gender', 'birthday'], []),
    _p(7, '收货地址列表', 'GET', '/api/users/addresses', '用户', '查询用户收货地址列表',
       [], ['addresses', 'total']),
    _p(8, '新增收货地址', 'POST', '/api/users/addresses', '用户', '添加收货地址',
       ['receiver', 'phone', 'province', 'city', 'district', 'detail', 'is_default'],
       ['address_id']),
    _p(9, '删除收货地址', 'DELETE', '/api/users/addresses/{address_id}', '用户', '删除收货地址',
       ['address_id'], []),
    _p(10, '实名认证', 'POST', '/api/users/verify-identity', '用户', '提交实名认证信息',
         ['real_name', 'id_card_no', 'id_card_front', 'id_card_back'], ['verify_status']),
    # 商品模块 (12)
    _p(11, '商品列表', 'GET', '/api/products', '商品', '分页查询商品列表',
       ['page', 'page_size', 'category_id', 'keyword', 'sort', 'min_price', 'max_price'],
       ['products', 'total', 'page']),
    _p(12, '商品详情', 'GET', '/api/products/{product_id}', '商品', '查询单个商品详细信息',
       ['product_id'], ['product_id', 'name', 'price', 'original_price', 'stock', 'description', 'images', 'skus']),
    _p(13, '商品搜索', 'GET', '/api/products/search', '商品', '关键词搜索商品',
       ['keyword', 'page', 'page_size', 'filters'], ['products', 'total', 'aggregations']),
    _p(14, '商品分类列表', 'GET', '/api/categories', '商品', '查询商品分类树',
       ['parent_id'], ['categories']),
    _p(15, '品牌列表', 'GET', '/api/brands', '商品', '查询品牌列表',
       ['category_id', 'keyword'], ['brands']),
    _p(16, '品牌详情', 'GET', '/api/brands/{brand_id}', '商品', '查询品牌详情',
       ['brand_id'], ['brand_id', 'name', 'logo', 'description']),
    _p(17, 'SKU查询', 'GET', '/api/products/{product_id}/skus', '商品', '查询商品SKU列表',
       ['product_id'], ['skus']),
    _p(18, '商品评价列表', 'GET', '/api/products/{product_id}/reviews', '商品', '查询商品评价',
       ['product_id', 'page', 'page_size', 'has_media'], ['reviews', 'total', 'avg_score']),
    _p(19, '商品规格查询', 'GET', '/api/products/{product_id}/specs', '商品', '查询商品规格信息',
       ['product_id'], ['specs']),
    _p(20, '商品库存查询', 'GET', '/api/products/{product_id}/stock', '商品', '查询商品库存',
       ['product_id', 'sku_id'], ['stock', 'available']),
    _p(21, '商品上架', 'POST', '/api/products/{product_id}/publish', '商品', '商品上架销售',
       ['product_id'], ['product_id', 'status']),
    _p(22, '商品下架', 'POST', '/api/products/{product_id}/unpublish', '商品', '商品下架',
       ['product_id'], ['product_id', 'status']),
    # 订单模块 (10)
    _p(23, '创建订单', 'POST', '/api/orders', '订单', '创建一个新的订单',
       ['product_id', 'quantity', 'price', 'address_id', 'coupon_code', 'remark'],
       ['order_id', 'status', 'total_amount']),
    _p(24, '订单列表', 'GET', '/api/orders', '订单', '查询用户订单列表',
       ['page', 'page_size', 'status'], ['orders', 'total']),
    _p(25, '订单详情', 'GET', '/api/orders/{order_id}', '订单', '查询订单详细信息',
       ['order_id'], ['order_id', 'status', 'items', 'total_amount', 'created_at', 'paid_at', 'shipped_at']),
    _p(26, '取消订单', 'POST', '/api/orders/{order_id}/cancel', '订单', '取消未支付订单',
       ['order_id', 'reason'], ['order_id', 'status']),
    _p(27, '确认收货', 'POST', '/api/orders/{order_id}/confirm', '订单', '买家确认收货',
       ['order_id'], ['order_id', 'status']),
    _p(28, '删除订单', 'DELETE', '/api/orders/{order_id}', '订单', '删除已完成的订单记录',
       ['order_id'], []),
    _p(29, '订单物流查询', 'GET', '/api/orders/{order_id}/logistics', '订单', '查询订单物流信息',
       ['order_id'], ['logistics_company', 'tracking_no', 'tracks']),
    _p(30, '申请开票', 'POST', '/api/orders/{order_id}/invoice', '订单', '申请开具发票',
       ['order_id', 'invoice_type', 'title', 'tax_no'], ['invoice_id', 'url']),
    _p(31, '订单评价', 'POST', '/api/orders/{order_id}/review', '订单', '对订单进行评价',
       ['order_id', 'rating', 'content', 'images'], ['review_id']),
    _p(32, '订单导出', 'GET', '/api/orders/export', '订单', '导出订单数据',
       ['date_from', 'date_to', 'status'], ['file_url']),
    # 购物车 (5)
    _p(33, '加入购物车', 'POST', '/api/cart/items', '购物车', '将商品加入购物车',
       ['product_id', 'quantity', 'sku_id'], ['cart_item_id', 'subtotal']),
    _p(34, '查看购物车', 'GET', '/api/cart', '购物车', '获取购物车列表',
       [], ['items', 'total_count', 'total_amount']),
    _p(35, '修改购物车数量', 'PUT', '/api/cart/items/{item_id}', '购物车', '修改购物车商品数量',
       ['item_id', 'quantity'], []),
    _p(36, '删除购物车商品', 'DELETE', '/api/cart/items/{item_id}', '购物车', '从购物车移除商品',
       ['item_id'], []),
    _p(37, '清空购物车', 'DELETE', '/api/cart', '购物车', '清空购物车所有商品',
       [], []),
    # 支付 (5)
    _p(38, '支付订单', 'POST', '/api/payments', '支付', '对订单发起支付',
       ['order_id', 'pay_method', 'amount'], ['payment_id', 'pay_url', 'status']),
    _p(39, '支付回调', 'POST', '/api/payments/callback', '支付', '支付渠道异步通知',
       ['trade_no', 'status', 'amount', 'sign'], []),
    _p(40, '查询支付状态', 'GET', '/api/payments/{payment_id}', '支付', '查询支付结果',
       ['payment_id'], ['payment_id', 'status', 'pay_time', 'amount']),
    _p(41, '申请退款', 'POST', '/api/refunds', '支付', '申请订单退款',
       ['order_id', 'refund_amount', 'reason'], ['refund_id', 'status']),
    _p(42, '退款详情', 'GET', '/api/refunds/{refund_id}', '支付', '查询退款进度',
       ['refund_id'], ['refund_id', 'status', 'amount', 'success_time']),
    # 营销 (8)
    _p(43, '优惠券列表', 'GET', '/api/coupons', '营销', '查询可用优惠券',
       ['page', 'page_size', 'status'], ['coupons', 'total']),
    _p(44, '领取优惠券', 'POST', '/api/coupons/{coupon_id}/claim', '营销', '领取优惠券',
       ['coupon_id'], ['user_coupon_id']),
    _p(45, '使用优惠券', 'POST', '/api/coupons/apply', '营销', '下单使用优惠券',
       ['coupon_code', 'order_id'], ['discount_amount', 'final_amount']),
    _p(46, '满减活动列表', 'GET', '/api/promotions', '营销', '查询满减促销活动',
       ['page', 'page_size'], ['promotions', 'total']),
    _p(47, '秒杀活动列表', 'GET', '/api/flash-sales', '营销', '查询秒杀活动',
       ['page', 'page_size'], ['flash_sales', 'total']),
    _p(48, '秒杀下单', 'POST', '/api/flash-sales/{activity_id}/order', '营销', '参与秒杀下单',
       ['activity_id', 'product_id', 'sku_id'], ['order_id']),
    _p(49, '积分查询', 'GET', '/api/points', '营销', '查询用户积分',
       [], ['total_points', 'expiring_points']),
    _p(50, '积分兑换', 'POST', '/api/points/redeem', '营销', '积分兑换商品',
       ['product_id', 'points_cost'], ['exchange_id']),
    # 售后 (5)
    _p(51, '申请售后', 'POST', '/api/aftersales', '售后', '申请退货或换货',
       ['order_id', 'type', 'reason', 'items'], ['aftersale_id', 'status']),
    _p(52, '售后详情', 'GET', '/api/aftersales/{aftersale_id}', '售后', '查询售后进度',
       ['aftersale_id'], ['aftersale_id', 'status', 'type', 'items']),
    _p(53, '售后列表', 'GET', '/api/aftersales', '售后', '查询售后记录列表',
       ['page', 'page_size', 'status'], ['aftersales', 'total']),
    _p(54, '撤销售后', 'POST', '/api/aftersales/{aftersale_id}/cancel', '售后', '撤销售后申请',
       ['aftersale_id'], ['aftersale_id', 'status']),
    _p(55, '填写退货物流', 'POST', '/api/aftersales/{aftersale_id}/ship-back', '售后', '填写退货物流单号',
       ['aftersale_id', 'logistics_company', 'tracking_no'], []),
    # 收藏/足迹 (5)
    _p(56, '收藏商品', 'POST', '/api/favorites', '收藏', '收藏商品',
       ['product_id'], []),
    _p(57, '取消收藏', 'DELETE', '/api/favorites/{product_id}', '收藏', '取消收藏商品',
       ['product_id'], []),
    _p(58, '收藏列表', 'GET', '/api/favorites', '收藏', '查询收藏列表',
       ['page', 'page_size'], ['favorites', 'total']),
    _p(59, '浏览足迹', 'GET', '/api/browsing-history', '收藏', '查询浏览历史',
       ['page', 'page_size'], ['history', 'total']),
    _p(60, '清除足迹', 'DELETE', '/api/browsing-history', '收藏', '清除浏览历史',
       [], []),
]

ECOMMERCE_CASES = [
    # 用户模块
    ('用户注册', 1, '基础'), ('注册账号', 1, '口语'), ('开户', 1, '术语'),
    ('用户登录', 2, '基础'), ('登录', 2, '口语'), ('登入系统', 2, '口语'),
    ('用户登出', 3, '基础'), ('退出登录', 3, '口语'), ('登出', 3, '口语'),
    ('修改密码', 4, '基础'), ('改密码', 4, '口语'), ('重置密码', 4, '口语'),
    ('查个人信息', 5, '口语'), ('看用户资料', 5, '口语'),
    ('改个人信息', 6, '口语'), ('更新资料', 6, '口语'),
    ('收货地址列表', 7, '基础'), ('查看地址', 7, '口语'),
    ('新增收货地址', 8, '基础'), ('添加地址', 8, '口语'), ('填收货地址', 8, '口语'),
    ('删除收货地址', 9, '基础'), ('删除地址', 9, '口语'),
    ('实名认证', 10, '基础'), ('身份认证', 10, '同义'), ('实名验证', 10, '同义'),
    # 商品模块
    ('商品列表', 11, '基础'), ('浏览商品', 11, '口语'), ('看商品', 11, '口语'),
    ('商品详情', 12, '基础'), ('看商品详情', 12, '口语'),
    ('商品搜索', 13, '基础'), ('搜商品', 13, '口语'), ('搜索东西', 13, '口语'),
    ('商品分类', 14, '基础'), ('看分类', 14, '口语'),
    ('品牌列表', 15, '基础'), ('查品牌', 15, '口语'),
    ('品牌详情', 16, '基础'), ('看品牌信息', 16, '口语'),
    ('查询SKU', 17, '口语'), ('看规格库存', 17, '口语'),
    ('看商品评价', 18, '口语'), ('查评价', 18, '口语'),
    ('查商品规格', 19, '口语'), ('看规格', 19, '口语'),
    ('查商品库存', 20, '口语'), ('还有货吗', 20, '问句'),
    ('商品上架', 21, '基础'), ('发布商品', 21, '同义'),
    ('商品下架', 22, '基础'), ('下架商品', 22, '倒序'),
    # 订单模块
    ('创建订单', 23, '基础'), ('下单', 23, '口语'), ('买东西', 23, '口语'),
    ('订单列表', 24, '基础'), ('查我的订单', 24, '口语'), ('看全部订单', 24, '口语'),
    ('订单详情', 25, '基础'), ('看订单信息', 25, '口语'), ('查订单', 25, '口语'),
    ('取消订单', 26, '基础'), ('退单', 26, '口语'), ('不想要了', 26, '口语'),
    ('确认收货', 27, '基础'), ('确认收到货了', 27, '口语'),
    ('删除订单', 28, '基础'), ('删订单', 28, '口语'),
    ('查物流', 29, '口语'), ('快递到哪了', 29, '问句'),
    ('开发票', 30, '口语'), ('申请发票', 30, '同义'),
    ('评价订单', 31, '口语'), ('写评价', 31, '口语'),
    ('导出订单', 32, '基础'), ('下载订单', 32, '同义'),
    # 购物车
    ('加入购物车', 33, '基础'), ('加购物车', 33, '口语'), ('加车', 33, '术语'),
    ('查看购物车', 34, '基础'), ('看购物车', 34, '口语'),
    ('修改购物车数量', 35, '基础'), ('改购物车数量', 35, '口语'),
    ('删除购物车商品', 36, '基础'), ('移除购物车', 36, '口语'),
    ('清空购物车', 37, '基础'), ('清购物车', 37, '口语'),
    # 支付
    ('支付订单', 38, '基础'), ('付钱', 38, '口语'), ('付款', 38, '口语'),
    ('支付回调', 39, '基础'), ('回调通知', 39, '同义'),
    ('查询支付状态', 40, '基础'), ('查支付结果', 40, '口语'), ('付成功了吗', 40, '问句'),
    ('申请退款', 41, '基础'), ('退款', 41, '口语'), ('退钱', 41, '口语'),
    ('退款详情', 42, '基础'), ('看退款进度', 42, '口语'),
    # 营销
    ('优惠券列表', 43, '基础'), ('查优惠券', 43, '口语'),
    ('领取优惠券', 44, '基础'), ('领券', 44, '口语'), ('领优惠券', 44, '口语'),
    ('使用优惠券', 45, '基础'), ('用优惠券', 45, '口语'), ('用券', 45, '口语'),
    ('满减活动', 46, '口语'), ('查促销', 46, '口语'),
    ('秒杀活动', 47, '口语'), ('看秒杀', 47, '口语'),
    ('秒杀下单', 48, '基础'), ('抢购', 48, '口语'),
    ('积分查询', 49, '基础'), ('查积分', 49, '口语'), ('多少积分', 49, '问句'),
    ('积分兑换', 50, '基础'), ('积分换东西', 50, '口语'),
    # 售后
    ('申请售后', 51, '基础'), ('退货', 51, '口语'), ('换货', 51, '口语'),
    ('售后详情', 52, '基础'), ('看售后进度', 52, '口语'),
    ('售后列表', 53, '基础'), ('查售后', 53, '口语'),
    ('撤销售后', 54, '基础'), ('取消退货', 54, '口语'),
    ('填写退货物流', 55, '基础'), ('填退货单号', 55, '口语'),
    # 收藏/足迹
    ('收藏商品', 56, '基础'), ('收藏', 56, '口语'),
    ('取消收藏', 57, '基础'), ('取消收藏', 57, '口语'),
    ('收藏列表', 58, '基础'), ('看收藏', 58, '口语'),
    ('浏览足迹', 59, '基础'), ('看历史', 59, '口语'),
    ('清除足迹', 60, '基础'), ('清空历史', 60, '口语'),
]

# ═══════════════════════════════════════════════════════════════
#  物流行业 60 接口
# ═══════════════════════════════════════════════════════════════
LOGISTICS = [
    # 运单管理 (10)
    _p(101, '创建运单', 'POST', '/api/waybills', '运单管理', '创建物流运单',
       ['sender_name', 'sender_phone', 'sender_address', 'receiver_name', 'receiver_phone', 'receiver_address', 'weight', 'volume'],
       ['waybill_no', 'status', 'estimated_delivery']),
    _p(102, '运单详情', 'GET', '/api/waybills/{waybill_no}', '运单管理', '查询运单详细信息',
       ['waybill_no'], ['waybill_no', 'status', 'sender', 'receiver', 'weight', 'create_time']),
    _p(103, '运单状态查询', 'GET', '/api/waybills/{waybill_no}/status', '运单管理', '查询运单当前状态',
       ['waybill_no'], ['waybill_no', 'status', 'current_node', 'update_time']),
    _p(104, '运单轨迹查询', 'GET', '/api/waybills/{waybill_no}/tracks', '运单管理', '查询运单物流轨迹',
       ['waybill_no'], ['waybill_no', 'tracks']),
    _p(105, '取消运单', 'POST', '/api/waybills/{waybill_no}/cancel', '运单管理', '取消未揽收的运单',
       ['waybill_no', 'reason'], ['waybill_no', 'status']),
    _p(106, '修改运单', 'PUT', '/api/waybills/{waybill_no}', '运单管理', '修改运单信息',
       ['waybill_no', 'receiver_name', 'receiver_phone', 'receiver_address'], []),
    _p(107, '运单列表', 'GET', '/api/waybills', '运单管理', '分页查询运单列表',
       ['page', 'page_size', 'status', 'date_from', 'date_to'], ['waybills', 'total']),
    _p(108, '批量创建运单', 'POST', '/api/waybills/batch', '运单管理', '批量创建运单',
       ['waybills'], ['results', 'success_count', 'fail_count']),
    _p(109, '打印面单', 'POST', '/api/waybills/{waybill_no}/print', '运单管理', '生成运单面单打印数据',
       ['waybill_no', 'template'], ['print_data', 'pdf_url']),
    _p(110, '运单评价', 'POST', '/api/waybills/{waybill_no}/review', '运单管理', '对运单服务评价',
       ['waybill_no', 'rating', 'comment'], ['review_id']),
    # 操作管理 (10)
    _p(111, '揽收', 'POST', '/api/waybills/{waybill_no}/pickup', '操作管理', '快递员揽收包裹',
       ['waybill_no', 'pickup_time', 'courier_id'], ['waybill_no', 'status']),
    _p(112, '派件', 'POST', '/api/waybills/{waybill_no}/deliver', '操作管理', '快递员开始派件',
       ['waybill_no', 'courier_id'], ['waybill_no', 'status']),
    _p(113, '签收', 'POST', '/api/waybills/{waybill_no}/sign', '操作管理', '收件人签收包裹',
       ['waybill_no', 'signer_name', 'sign_time'], ['waybill_no', 'status']),
    _p(114, '拒收', 'POST', '/api/waybills/{waybill_no}/reject', '操作管理', '收件人拒收包裹',
       ['waybill_no', 'reason'], ['waybill_no', 'status']),
    _p(115, '转投', 'POST', '/api/waybills/{waybill_no}/redirect', '操作管理', '转投到其他网点',
       ['waybill_no', 'target_station_id', 'reason'], ['waybill_no', 'status']),
    _p(116, '称重复核', 'POST', '/api/waybills/{waybill_no}/reweigh', '操作管理', '复核包裹重量',
       ['waybill_no', 'actual_weight'], ['waybill_no', 'weight_diff', 'extra_fee']),
    _p(117, '入库', 'POST', '/api/stations/{station_id}/inbound', '操作管理', '包裹入库网点',
       ['station_id', 'waybill_no', 'operator_id'], []),
    _p(118, '出库', 'POST', '/api/stations/{station_id}/outbound', '操作管理', '包裹出库网点',
       ['station_id', 'waybill_no', 'operator_id', 'next_station_id'], []),
    _p(119, '问题件登记', 'POST', '/api/waybills/{waybill_no}/issue', '操作管理', '登记问题件',
       ['waybill_no', 'issue_type', 'description', 'photos'], ['issue_id']),
    _p(120, '快件类型标记', 'POST', '/api/waybills/{waybill_no}/mark-type', '操作管理', '标记快件类型',
       ['waybill_no', 'type'], []),
    # 网点管理 (8)
    _p(121, '网点列表', 'GET', '/api/stations', '网点管理', '查询物流网点',
       ['city', 'district', 'type'], ['stations']),
    _p(122, '网点详情', 'GET', '/api/stations/{station_id}', '网点管理', '查询网点详细信息',
       ['station_id'], ['station_id', 'name', 'address', 'phone', 'capacity']),
    _p(123, '网点库存查询', 'GET', '/api/stations/{station_id}/inventory', '网点管理', '查询网点在库包裹数',
       ['station_id', 'status'], ['count', 'waybills']),
    _p(124, '网点工作量统计', 'GET', '/api/stations/{station_id}/workload', '网点管理', '查询网点工作量',
       ['station_id', 'date'], ['pickup_count', 'deliver_count', 'inbound_count', 'outbound_count']),
    _p(125, '新增网点', 'POST', '/api/stations', '网点管理', '新增物流网点',
       ['name', 'city', 'district', 'address', 'phone', 'capacity'], ['station_id']),
    _p(126, '修改网点', 'PUT', '/api/stations/{station_id}', '网点管理', '修改网点信息',
       ['station_id', 'name', 'address', 'phone'], []),
    _p(127, '停用网点', 'POST', '/api/stations/{station_id}/disable', '网点管理', '停用网点',
       ['station_id', 'reason'], []),
    _p(128, '网点覆盖区域', 'GET', '/api/stations/{station_id}/coverage', '网点管理', '查询网点配送范围',
       ['station_id'], ['areas']),
    # 计费管理 (7)
    _p(129, '运费计算', 'POST', '/api/freight/calculate', '计费管理', '计算运费',
       ['origin', 'destination', 'weight', 'volume', 'service_type'],
       ['freight', 'estimated_days']),
    _p(130, '保价费计算', 'POST', '/api/freight/insurance', '计费管理', '计算保价费用',
       ['declared_value', 'service_type'], ['insurance_fee']),
    _p(131, '代收货款', 'POST', '/api/cod/apply', '计费管理', '申请代收货款服务',
       ['waybill_no', 'cod_amount'], ['cod_id', 'status']),
    _p(132, '代收货款查询', 'GET', '/api/cod/{cod_id}', '计费管理', '查询代收货款状态',
       ['cod_id'], ['cod_id', 'status', 'amount', 'settlement_time']),
    _p(133, '账单查询', 'GET', '/api/bills', '计费管理', '查询客户账单',
       ['customer_id', 'month', 'status'], ['bills', 'total']),
    _p(134, '账单明细', 'GET', '/api/bills/{bill_id}/details', '计费管理', '查询账单明细',
       ['bill_id'], ['details']),
    _p(135, '账单结算', 'POST', '/api/bills/{bill_id}/settle', '计费管理', '结算账单',
       ['bill_id', 'pay_method'], ['settlement_id', 'status']),
    # 人员管理 (6)
    _p(136, '快递员列表', 'GET', '/api/couriers', '人员管理', '查询快递员列表',
       ['station_id', 'status'], ['couriers']),
    _p(137, '快递员详情', 'GET', '/api/couriers/{courier_id}', '人员管理', '查询快递员详情',
       ['courier_id'], ['courier_id', 'name', 'phone', 'station', 'status']),
    _p(138, '快递员排班', 'POST', '/api/couriers/{courier_id}/schedule', '人员管理', '设置快递员排班',
       ['courier_id', 'date', 'shift', 'area'], []),
    _p(139, '快递员位置', 'GET', '/api/couriers/{courier_id}/location', '人员管理', '查询快递员实时位置',
       ['courier_id'], ['lat', 'lng', 'update_time']),
    _p(140, '快递员绩效', 'GET', '/api/couriers/{courier_id}/performance', '人员管理', '查询快递员绩效',
       ['courier_id', 'month'], ['pickup_count', 'deliver_count', 'complaint_count', 'score']),
    _p(141, '快递员上线', 'POST', '/api/couriers/{courier_id}/online', '人员管理', '快递员上线接单',
       ['courier_id'], ['courier_id', 'status']),
    # 异常管理 (5)
    _p(142, '异常上报', 'POST', '/api/exceptions', '异常管理', '上报表件异常',
       ['waybill_no', 'exception_type', 'description', 'photos'], ['exception_id', 'status']),
    _p(143, '异常处理', 'POST', '/api/exceptions/{exception_id}/handle', '异常管理', '处理异常件',
       ['exception_id', 'action', 'result'], ['exception_id', 'status']),
    _p(144, '理赔申请', 'POST', '/api/claims', '异常管理', '申请包裹理赔',
       ['waybill_no', 'claim_type', 'amount', 'evidence'], ['claim_id', 'status']),
    _p(145, '理赔详情', 'GET', '/api/claims/{claim_id}', '异常管理', '查询理赔进度',
       ['claim_id'], ['claim_id', 'status', 'amount', 'result']),
    _p(146, '投诉提交', 'POST', '/api/complaints', '异常管理', '提交服务投诉',
       ['waybill_no', 'type', 'content'], ['complaint_id']),
    # 调度统计 (8)
    _p(147, '调度任务查询', 'GET', '/api/dispatch/tasks', '调度统计', '查询调度任务',
       ['station_id', 'date', 'status'], ['tasks']),
    _p(148, '路线规划', 'POST', '/api/dispatch/route-plan', '调度统计', '规划配送路线',
       ['station_id', 'waybill_nos'], ['routes']),
    _p(149, '车辆管理', 'GET', '/api/vehicles', '调度统计', '查询车辆列表',
       ['station_id', 'status'], ['vehicles']),
    _p(150, '业务量统计', 'GET', '/api/stats/volume', '调度统计', '统计业务量',
       ['date_from', 'date_to', 'station_id'], ['daily_volume']),
    _p(151, '时效统计', 'GET', '/api/stats/timeliness', '调度统计', '统计配送时效',
       ['date_from', 'date_to', 'station_id'], ['avg_hours', 'on_time_rate']),
    _p(152, '客户投诉统计', 'GET', '/api/stats/complaints', '调度统计', '统计投诉数据',
       ['date_from', 'date_to'], ['complaint_count', 'by_type']),
    _p(153, '收入统计', 'GET', '/api/stats/revenue', '调度统计', '统计收入数据',
       ['date_from', 'date_to', 'station_id'], ['total_revenue', 'by_service']),
    _p(154, '区域热力图', 'GET', '/api/stats/heatmap', '调度统计', '查询区域订单热力分布',
       ['city', 'date'], ['heatmap_data']),
    # 客户管理 (6)
    _p(155, '客户列表', 'GET', '/api/customers', '客户管理', '查询客户列表',
       ['page', 'page_size', 'keyword'], ['customers', 'total']),
    _p(156, '客户详情', 'GET', '/api/customers/{customer_id}', '客户管理', '查询客户详情',
       ['customer_id'], ['customer_id', 'name', 'phone', 'type', 'contract']),
    _p(157, '客户地址簿', 'GET', '/api/customers/{customer_id}/addresses', '客户管理', '查询客户地址簿',
       ['customer_id'], ['addresses']),
    _p(158, '合同管理', 'GET', '/api/contracts', '客户管理', '查询客户合同列表',
       ['customer_id', 'status'], ['contracts']),
    _p(159, '协议价设置', 'POST', '/api/customers/{customer_id}/pricing', '客户管理', '设置客户协议价',
       ['customer_id', 'service_type', 'price_per_kg'], []),
    _p(160, '客户下单', 'POST', '/api/customers/{customer_id}/orders', '客户管理', '企业客户批量下单',
       ['customer_id', 'waybills'], ['results']),
]

LOGISTICS_CASES = [
    # 运单管理
    ('创建运单', 101, '基础'), ('寄件', 101, '口语'), ('发快递', 101, '口语'), ('寄包裹', 101, '口语'),
    ('运单详情', 102, '基础'), ('查运单', 102, '口语'),
    ('运单状态查询', 103, '基础'), ('查物流状态', 103, '口语'), ('快递到哪了', 103, '问句'),
    ('运单轨迹查询', 104, '基础'), ('查物流轨迹', 104, '口语'), ('看配送进度', 104, '口语'),
    ('取消运单', 105, '基础'), ('取消快递', 105, '口语'),
    ('修改运单', 106, '基础'), ('改收件人', 106, '口语'),
    ('运单列表', 107, '基础'), ('看运单列表', 107, '口语'),
    ('批量创建运单', 108, '基础'), ('批量寄件', 108, '口语'),
    ('打印面单', 109, '基础'), ('打面单', 109, '口语'),
    ('运单评价', 110, '基础'), ('评价快递服务', 110, '口语'),
    # 操作管理
    ('揽收', 111, '基础'), ('取件', 111, '口语'), ('快递员上门', 111, '口语'),
    ('派件', 112, '基础'), ('派送', 112, '口语'), ('送快递', 112, '口语'),
    ('签收', 113, '基础'), ('确认收件', 113, '口语'), ('取快递', 113, '口语'),
    ('拒收', 114, '基础'), ('拒签', 114, '口语'),
    ('转投', 115, '基础'), ('转寄', 115, '口语'),
    ('称重复核', 116, '基础'), ('复核重量', 116, '口语'),
    ('入库', 117, '基础'), ('包裹入库', 117, '口语'),
    ('出库', 118, '基础'), ('包裹出库', 118, '口语'),
    ('问题件登记', 119, '基础'), ('登记问题件', 119, '口语'),
    ('快件类型标记', 120, '基础'), ('标记类型', 120, '口语'),
    # 网点管理
    ('网点列表', 121, '基础'), ('查网点', 121, '口语'), ('附近网点', 121, '口语'),
    ('网点详情', 122, '基础'), ('看网点信息', 122, '口语'),
    ('网点库存查询', 123, '基础'), ('网点有多少包裹', 123, '口语'),
    ('网点工作量统计', 124, '基础'), ('看网点工作量', 124, '口语'),
    ('新增网点', 125, '基础'), ('添加网点', 125, '口语'),
    ('修改网点', 126, '基础'), ('编辑网点', 126, '口语'),
    ('停用网点', 127, '基础'), ('关网点', 127, '口语'),
    ('网点覆盖区域', 128, '基础'), ('看配送范围', 128, '口语'),
    # 计费
    ('运费计算', 129, '基础'), ('算运费', 129, '口语'), ('邮费多少', 129, '问句'),
    ('保价费计算', 130, '基础'), ('算保价费', 130, '口语'),
    ('代收货款', 131, '基础'), ('申请代收', 131, '口语'),
    ('代收货款查询', 132, '基础'), ('查代收状态', 132, '口语'),
    ('账单查询', 133, '基础'), ('查账单', 133, '口语'),
    ('账单明细', 134, '基础'), ('看账单详情', 134, '口语'),
    ('账单结算', 135, '基础'), ('结算账单', 135, '口语'),
    # 人员
    ('快递员列表', 136, '基础'), ('查快递员', 136, '口语'),
    ('快递员详情', 137, '基础'), ('看快递员信息', 137, '口语'),
    ('快递员排班', 138, '基础'), ('排班', 138, '口语'),
    ('快递员位置', 139, '基础'), ('快递员在哪', 139, '问句'),
    ('快递员绩效', 140, '基础'), ('看绩效', 140, '口语'),
    ('快递员上线', 141, '基础'), ('上线接单', 141, '口语'),
    # 异常
    ('异常上报', 142, '基础'), ('报异常', 142, '口语'), ('包裹破损上报', 142, '口语'),
    ('异常处理', 143, '基础'), ('处理异常件', 143, '口语'),
    ('理赔申请', 144, '基础'), ('申请理赔', 144, '口语'), ('包裹丢失索赔', 144, '口语'),
    ('理赔详情', 145, '基础'), ('看理赔进度', 145, '口语'),
    ('投诉提交', 146, '基础'), ('投诉', 146, '口语'), ('投诉快递', 146, '口语'),
    # 调度统计
    ('调度任务查询', 147, '基础'), ('查调度', 147, '口语'),
    ('路线规划', 148, '基础'), ('规划送货路线', 148, '口语'),
    ('车辆管理', 149, '基础'), ('查车辆', 149, '口语'),
    ('业务量统计', 150, '基础'), ('看单量', 150, '口语'),
    ('时效统计', 151, '基础'), ('看配送时效', 151, '口语'),
    ('客户投诉统计', 152, '基础'), ('投诉数据', 152, '口语'),
    ('收入统计', 153, '基础'), ('看收入', 153, '口语'),
    ('区域热力图', 154, '基础'), ('看热力图', 154, '口语'),
    # 客户
    ('客户列表', 155, '基础'), ('查客户', 155, '口语'),
    ('客户详情', 156, '基础'), ('看客户信息', 156, '口语'),
    ('客户地址簿', 157, '基础'), ('查客户地址', 157, '口语'),
    ('合同管理', 158, '基础'), ('查合同', 158, '口语'),
    ('协议价设置', 159, '基础'), ('设协议价', 159, '口语'),
    ('客户下单', 160, '基础'), ('企业客户寄件', 160, '口语'),
]

# ═══════════════════════════════════════════════════════════════
#  ERP 行业 60 接口
# ═══════════════════════════════════════════════════════════════
ERP = [
    # 采购管理 (10)
    _p(201, '创建采购单', 'POST', '/api/purchase/orders', '采购管理', '创建采购订单',
       ['supplier_id', 'items', 'expected_date', 'warehouse_id'], ['purchase_order_id', 'status']),
    _p(202, '采购单列表', 'GET', '/api/purchase/orders', '采购管理', '查询采购�单列表',
       ['page', 'page_size', 'status', 'supplier_id'], ['orders', 'total']),
    _p(203, '采购单详情', 'GET', '/api/purchase/orders/{order_id}', '采购管理', '查询采购单详情',
       ['order_id'], ['order_id', 'status', 'supplier', 'items', 'total_amount']),
    _p(204, '采购入库', 'POST', '/api/inbound/purchase', '入库管理', '采购到货入库',
       ['purchase_order_id', 'items', 'actual_quantity', 'warehouse_id'], ['inbound_order_id', 'status']),
    _p(205, '采购退货', 'POST', '/api/purchase/returns', '采购管理', '采购退货给供应商',
       ['purchase_order_id', 'items', 'reason'], ['return_id', 'status']),
    _p(206, '供应商列表', 'GET', '/api/suppliers', '供应商管理', '查询供应商列表',
       ['page', 'keyword', 'category'], ['suppliers', 'total']),
    _p(207, '供应商详情', 'GET', '/api/suppliers/{supplier_id}', '供应商管理', '查询供应商详情',
       ['supplier_id'], ['supplier_id', 'name', 'contact', 'category', 'rating']),
    _p(208, '新增供应商', 'POST', '/api/suppliers', '供应商管理', '新增供应商',
       ['name', 'contact', 'phone', 'category', 'address'], ['supplier_id']),
    _p(209, '采购报价查询', 'GET', '/api/purchase/quotes', '采购管理', '查询供应商报价',
       ['supplier_id', 'product_id'], ['quotes']),
    _p(210, '采购审批', 'POST', '/api/purchase/orders/{order_id}/approve', '采购管理', '审批采购单',
       ['order_id', 'action', 'comment'], ['order_id', 'status']),
    # 销售管理 (10)
    _p(211, '创建销售订单', 'POST', '/api/sales/orders', '销售管理', '创建销售订单',
       ['customer_id', 'items', 'delivery_date', 'payment_terms'], ['sales_order_id', 'status']),
    _p(212, '销售订单列表', 'GET', '/api/sales/orders', '销售管理', '查询销售单列表',
       ['page', 'page_size', 'status', 'customer_id'], ['orders', 'total']),
    _p(213, '销售订单详情', 'GET', '/api/sales/orders/{order_id}', '销售管理', '查询销售单详情',
       ['order_id'], ['order_id', 'status', 'customer', 'items', 'total_amount']),
    _p(214, '销售出库', 'POST', '/api/outbound/sales', '出库管理', '根据销售单出库',
       ['sales_order_id', 'items', 'warehouse_id'], ['outbound_order_id', 'status']),
    _p(215, '销售退货', 'POST', '/api/sales/returns', '销售管理', '客户退货入库',
       ['sales_order_id', 'items', 'reason'], ['return_id', 'status']),
    _p(216, '客户列表', 'GET', '/api/customers', '客户管理', '查询客户列表',
       ['page', 'keyword', 'level'], ['customers', 'total']),
    _p(217, '客户详情', 'GET', '/api/customers/{customer_id}', '客户管理', '查询客户详情',
       ['customer_id'], ['customer_id', 'name', 'contact', 'level', 'credit_limit']),
    _p(218, '报价单创建', 'POST', '/api/sales/quotes', '销售管理', '创建报价单',
       ['customer_id', 'items', 'valid_until'], ['quote_id']),
    _p(219, '销售审批', 'POST', '/api/sales/orders/{order_id}/approve', '销售管理', '审批销售单',
       ['order_id', 'action', 'comment'], ['order_id', 'status']),
    _p(220, '销售统计', 'GET', '/api/sales/stats', '销售管理', '销售数据统计',
       ['date_from', 'date_to', 'group_by'], ['total_amount', 'order_count', 'by_group']),
    # 库存管理 (10)
    _p(221, '库存查询', 'GET', '/api/inventory', '库存管理', '查询商品库存',
       ['product_id', 'warehouse_id', 'sku_code'], ['quantity', 'available_quantity', 'locked_quantity']),
    _p(222, '库存盘点', 'POST', '/api/inventory/check', '库存管理', '创建盘点任务',
       ['warehouse_id', 'check_items'], ['check_id', 'status']),
    _p(223, '库存调拨', 'POST', '/api/inventory/transfer', '库存管理', '仓库间库存调拨',
       ['from_warehouse', 'to_warehouse', 'items'], ['transfer_id', 'status']),
    _p(224, '库存预警列表', 'GET', '/api/inventory/alerts', '库存管理', '查询库存预警',
       ['warehouse_id', 'level'], ['alerts']),
    _p(225, '批次管理', 'GET', '/api/inventory/batches', '库存管理', '查询批次信息',
       ['product_id', 'warehouse_id'], ['batches']),
    _p(226, '库存锁定', 'POST', '/api/inventory/lock', '库存管理', '锁定库存',
       ['order_id', 'items', 'warehouse_id'], ['lock_id']),
    _p(227, '库存解锁', 'POST', '/api/inventory/unlock', '库存管理', '解锁库存',
       ['lock_id'], []),
    _p(228, '库存流水', 'GET', '/api/inventory/logs', '库存管理', '查询库存变动记录',
       ['product_id', 'warehouse_id', 'date_from', 'date_to'], ['logs']),
    _p(229, '其他入库', 'POST', '/api/inbound/misc', '入库管理', '非采购入库',
       ['warehouse_id', 'items', 'reason'], ['inbound_order_id']),
    _p(230, '其他出库', 'POST', '/api/outbound/misc', '出库管理', '非销售出库',
       ['warehouse_id', 'items', 'reason'], ['outbound_order_id']),
    # 生产管理 (8)
    _p(231, '创建生产工单', 'POST', '/api/production/orders', '生产管理', '创建生产工单',
       ['product_id', 'quantity', 'planned_start', 'planned_end'], ['production_order_id', 'status']),
    _p(232, '生产工单列表', 'GET', '/api/production/orders', '生产管理', '查询工单列表',
       ['page', 'page_size', 'status'], ['orders', 'total']),
    _p(233, 'BOM查询', 'GET', '/api/production/boms/{product_id}', '生产管理', '查询物料清单',
       ['product_id'], ['bom_items']),
    _p(234, '工序报工', 'POST', '/api/production/orders/{order_id}/report', '生产管理', '工序完工报告',
       ['order_id', 'process_id', 'quantity', 'worker_id'], []),
    _p(235, '生产领料', 'POST', '/api/production/orders/{order_id}/pick', '生产管理', '生产领料出库',
       ['order_id', 'items'], ['pick_order_id']),
    _p(236, '生产入库', 'POST', '/api/production/orders/{order_id}/stock-in', '生产管理', '产成品入库',
       ['order_id', 'quantity', 'warehouse_id'], ['inbound_order_id']),
    _p(237, '生产排程', 'POST', '/api/production/schedule', '生产管理', '生产排程',
       ['order_ids', 'resources'], ['schedule']),
    _p(238, '设备管理', 'GET', '/api/production/equipment', '生产管理', '查询设备列表',
       ['workshop_id', 'status'], ['equipment']),
    # 财务管理 (8)
    _p(239, '创建凭证', 'POST', '/api/finance/vouchers', '财务管理', '生成会计凭证',
       ['source_type', 'source_id', 'entries'], ['voucher_id', 'voucher_no']),
    _p(240, '凭证列表', 'GET', '/api/finance/vouchers', '财务管理', '查询凭证列表',
       ['page', 'date_from', 'date_to', 'status'], ['vouchers', 'total']),
    _p(241, '查询财务科目', 'GET', '/api/finance/accounts', '财务管理', '查询会计科目',
       ['account_type', 'level'], ['accounts']),
    _p(242, '收款登记', 'POST', '/api/finance/receipts', '财务管理', '登记收款',
       ['customer_id', 'amount', 'order_id', 'pay_method'], ['receipt_id']),
    _p(243, '付款登记', 'POST', '/api/finance/payments', '财务管理', '登记付款',
       ['supplier_id', 'amount', 'order_id', 'pay_method'], ['payment_id']),
    _p(244, '发票管理', 'GET', '/api/finance/invoices', '财务管理', '查询发票列表',
       ['page', 'type', 'status'], ['invoices', 'total']),
    _p(245, '发票开具', 'POST', '/api/finance/invoices', '财务管理', '开具发票',
       ['order_id', 'type', 'title', 'tax_no', 'amount'], ['invoice_id', 'invoice_no']),
    _p(246, '成本核算', 'POST', '/api/finance/cost-calc', '财务管理', '成本核算',
       ['product_id', 'period'], ['material_cost', 'labor_cost', 'overhead_cost', 'total']),
    # 审批管理 (4)
    _p(247, '审批单据', 'POST', '/api/approvals/{approval_id}/approve', '审批管理', '审批通过或驳回',
       ['approval_id', 'action', 'comment'], ['approval_id', 'status']),
    _p(248, '审批列表', 'GET', '/api/approvals', '审批管理', '查询待审批列表',
       ['page', 'type', 'status'], ['approvals', 'total']),
    _p(249, '审批流配置', 'GET', '/api/approvals/flows', '审批管理', '查询审批流配置',
       ['type'], ['flows']),
    _p(250, '审批流创建', 'POST', '/api/approvals/flows', '审批管理', '创建审批流',
       ['name', 'type', 'nodes'], ['flow_id']),
    # 人力管理 (6)
    _p(251, '员工列表', 'GET', '/api/hr/employees', '人力管理', '查询员工列表',
       ['page', 'department_id', 'status'], ['employees', 'total']),
    _p(252, '员工详情', 'GET', '/api/hr/employees/{employee_id}', '人力管理', '查询员工详情',
       ['employee_id'], ['employee_id', 'name', 'department', 'position', 'hire_date']),
    _p(253, '考勤记录', 'GET', '/api/hr/attendance', '人力管理', '查询考勤记录',
       ['employee_id', 'date_from', 'date_to'], ['records']),
    _p(254, '薪资计算', 'POST', '/api/hr/payroll/calculate', '人力管理', '计算月度薪资',
       ['month', 'department_id'], ['payroll_id']),
    _p(255, '薪资发放', 'POST', '/api/hr/payroll/{payroll_id}/pay', '人力管理', '发放薪资',
       ['payroll_id'], ['status']),
    _p(256, '招聘需求', 'POST', '/api/hr/recruitments', '人力管理', '提交招聘需求',
       ['position', 'count', 'department_id', 'requirements'], ['recruitment_id']),
    # 报表 (4)
    _p(257, '报表查询', 'GET', '/api/reports/{report_type}', '报表管理', '查询业务报表',
       ['report_type', 'date_from', 'date_to'], ['report_data']),
    _p(258, '利润报表', 'GET', '/api/reports/profit', '报表管理', '查询利润报表',
       ['date_from', 'date_to', 'dimension'], ['profit_data']),
    _p(259, '应收报表', 'GET', '/api/reports/receivable', '报表管理', '查询应收账款报表',
       ['date_from', 'date_to', 'customer_id'], ['receivable_data']),
    _p(260, '应付报表', 'GET', '/api/reports/payable', '报表管理', '查询应付账款报表',
       ['date_from', 'date_to', 'supplier_id'], ['payable_data']),
]

ERP_CASES = [
    # 采购
    ('创建采购单', 201, '基础'), ('下采购订单', 201, '口语'), ('新建采购', 201, '口语'),
    ('采购单列表', 202, '基础'), ('查采购单', 202, '口语'),
    ('采购单详情', 203, '基础'), ('看采购单信息', 203, '口语'),
    ('采购入库', 204, '基础'), ('到货入库', 204, '口语'), ('入库', 204, '口语'),
    ('采购退货', 205, '基础'), ('退供应商', 205, '口语'),
    ('供应商列表', 206, '基础'), ('查供应商', 206, '口语'),
    ('供应商详情', 207, '基础'), ('看供应商信息', 207, '口语'),
    ('新增供应商', 208, '基础'), ('添加供应商', 208, '口语'),
    ('采购报价查询', 209, '基础'), ('查报价', 209, '口语'),
    ('采购审批', 210, '基础'), ('审批采购', 210, '口语'),
    # 销售
    ('创建销售订单', 211, '基础'), ('下销售单', 211, '口语'), ('新建销售单', 211, '口语'),
    ('销售订单列表', 212, '基础'), ('查销售单', 212, '口语'),
    ('销售订单详情', 213, '基础'), ('看销售单信息', 213, '口语'),
    ('销售出库', 214, '基础'), ('发货出库', 214, '口语'), ('出库', 214, '口语'),
    ('销售退货', 215, '基础'), ('客户退货', 215, '口语'),
    ('客户列表', 216, '基础'), ('查客户', 216, '口语'),
    ('客户详情', 217, '基础'), ('看客户信息', 217, '口语'),
    ('报价单创建', 218, '基础'), ('创建报价', 218, '口语'),
    ('销售审批', 219, '基础'), ('审批销售', 219, '口语'),
    ('销售统计', 220, '基础'), ('看销售数据', 220, '口语'),
    # 库存
    ('库存查询', 221, '基础'), ('查库存', 221, '口语'), ('库存有多少', 221, '问句'),
    ('库存盘点', 222, '基础'), ('盘点', 222, '口语'),
    ('库存调拨', 223, '基础'), ('调拨', 223, '口语'),
    ('库存预警', 224, '口语'), ('库存不足提醒', 224, '口语'),
    ('批次管理', 225, '基础'), ('查批次', 225, '口语'),
    ('库存锁定', 226, '基础'), ('锁库存', 226, '口语'),
    ('库存解锁', 227, '基础'), ('解锁库存', 227, '口语'),
    ('库存流水', 228, '基础'), ('查库存变动', 228, '口语'),
    ('其他入库', 229, '基础'), ('杂项入库', 229, '口语'),
    ('其他出库', 230, '基础'), ('杂项出库', 230, '口语'),
    # 生产
    ('创建生产工单', 231, '基础'), ('创建工单', 231, '口语'), ('安排生产', 231, '口语'),
    ('生产工单列表', 232, '基础'), ('查工单', 232, '口语'),
    ('BOM查询', 233, '基础'), ('查物料清单', 233, '口语'),
    ('工序报工', 234, '基础'), ('报工', 234, '口语'),
    ('生产领料', 235, '基础'), ('领料', 235, '口语'),
    ('生产入库', 236, '基础'), ('产成品入库', 236, '口语'),
    ('生产排程', 237, '基础'), ('排产', 237, '口语'),
    ('设备管理', 238, '基础'), ('查设备', 238, '口语'),
    # 财务
    ('创建凭证', 239, '基础'), ('做账', 239, '术语'), ('生成凭证', 239, '口语'),
    ('凭证列表', 240, '基础'), ('查凭证', 240, '口语'),
    ('查询财务科目', 241, '基础'), ('查科目', 241, '口语'),
    ('收款登记', 242, '基础'), ('登记收款', 242, '口语'), ('收钱', 242, '口语'),
    ('付款登记', 243, '基础'), ('登记付款', 243, '口语'), ('付钱', 243, '口语'),
    ('发票管理', 244, '基础'), ('查发票', 244, '口语'),
    ('发票开具', 245, '基础'), ('开发票', 245, '口语'),
    ('成本核算', 246, '基础'), ('算成本', 246, '口语'),
    # 审批
    ('审批单据', 247, '基础'), ('审批', 247, '口语'), ('审批通过', 247, '口语'),
    ('审批列表', 248, '基础'), ('查待审批', 248, '口语'),
    ('审批流配置', 249, '基础'), ('看审批流', 249, '口语'),
    ('审批流创建', 250, '基础'), ('建审批流', 250, '口语'),
    # 人力
    ('员工列表', 251, '基础'), ('查员工', 251, '口语'),
    ('员工详情', 252, '基础'), ('看员工信息', 252, '口语'),
    ('考勤记录', 253, '基础'), ('查考勤', 253, '口语'),
    ('薪资计算', 254, '基础'), ('算工资', 254, '口语'),
    ('薪资发放', 255, '基础'), ('发工资', 255, '口语'),
    ('招聘需求', 256, '基础'), ('提招聘需求', 256, '口语'),
    # 报表
    ('报表查询', 257, '基础'), ('查报表', 257, '口语'),
    ('利润报表', 258, '基础'), ('看利润', 258, '口语'),
    ('应收报表', 259, '基础'), ('查应收', 259, '口语'),
    ('应付报表', 260, '基础'), ('查应付', 260, '口语'),
]

# ═══════════════════════════════════════════════════════════════
#  金融行业 60 接口
# ═══════════════════════════════════════════════════════════════
FINANCE = [
    # 账户管理 (10)
    _p(301, '开户', 'POST', '/api/accounts', '账户管理', '为客户开立银行账户',
       ['customer_id', 'account_type', 'currency', 'branch_id'], ['account_no', 'status']),
    _p(302, '账户查询', 'GET', '/api/accounts/{account_no}', '账户管理', '根据账号查询账户',
       ['account_no'], ['account_no', 'balance', 'status', 'account_type', 'currency']),
    _p(303, '销户', 'POST', '/api/accounts/{account_no}/close', '账户管理', '注销账户',
       ['account_no', 'reason'], ['account_no', 'status']),
    _p(304, '账户冻结', 'POST', '/api/accounts/{account_no}/freeze', '账户管理', '冻结账户',
       ['account_no', 'reason', 'operator_id'], ['account_no', 'status']),
    _p(305, '账户解冻', 'POST', '/api/accounts/{account_no}/unfreeze', '账户管理', '解冻账户',
       ['account_no', 'operator_id'], ['account_no', 'status']),
    _p(306, '账户列表', 'GET', '/api/accounts', '账户管理', '查询账户列表',
       ['customer_id', 'account_type', 'status', 'page'], ['accounts', 'total']),
    _p(307, '账户余额查询', 'GET', '/api/accounts/{account_no}/balance', '账户管理', '查询账户余额',
       ['account_no'], ['balance', 'available_balance', 'frozen_amount']),
    _p(308, '账户交易限额查询', 'GET', '/api/accounts/{account_no}/limits', '账户管理', '查询交易限额',
       ['account_no'], ['daily_limit', 'single_limit', 'remaining']),
    _p(309, '账户交易限额修改', 'PUT', '/api/accounts/{account_no}/limits', '账户管理', '修改交易限额',
       ['account_no', 'daily_limit', 'single_limit'], []),
    _p(310, '账户密码重置', 'POST', '/api/accounts/{account_no}/reset-password', '账户管理', '重置账户密码',
       ['account_no', 'new_password', 'verify_code'], []),
    # 存取款 (8)
    _p(311, '存款', 'POST', '/api/accounts/{account_no}/deposit', '存取款', '向账户存入资金',
       ['account_no', 'amount', 'currency'], ['transaction_id', 'balance']),
    _p(312, '取款', 'POST', '/api/accounts/{account_no}/withdraw', '存取款', '从账户取出资金',
       ['account_no', 'amount', 'currency', 'password'], ['transaction_id', 'balance']),
    _p(313, '存款产品列表', 'GET', '/api/deposit/products', '存取款', '查询存款产品',
       ['currency', 'term_type'], ['products']),
    _p(314, '定期存款开户', 'POST', '/api/deposit/fixed', '存取款', '开立定期存款',
       ['account_no', 'product_id', 'amount', 'term_months'], ['deposit_id', 'maturity_date', 'interest_rate']),
    _p(315, '定期存款支取', 'POST', '/api/deposit/fixed/{deposit_id}/withdraw', '存取款', '提前支取定期存款',
       ['deposit_id', 'amount'], ['transaction_id', 'interest']),
    _p(316, '通知存款', 'POST', '/api/deposit/notice', '存取款', '开立通知存款',
       ['account_no', 'amount', 'notice_days'], ['deposit_id']),
    _p(317, '大额存单查询', 'GET', '/api/deposit/cd', '存取款', '查询大额存单产品',
       ['amount', 'term'], ['certificates']),
    _p(318, '利息计算', 'POST', '/api/deposit/interest-calc', '存取款', '计算存款利息',
       ['amount', 'term_days', 'interest_rate'], ['interest', 'tax', 'net_interest']),
    # 转账汇款 (8)
    _p(319, '转账', 'POST', '/api/transfers', '转账汇款', '账户间转账',
       ['from_account', 'to_account', 'amount', 'currency', 'remark'], ['transfer_id', 'status']),
    _p(320, '转账记录查询', 'GET', '/api/transfers', '转账汇款', '查询转账记录',
       ['account_no', 'date_from', 'date_to', 'page'], ['transfers', 'total']),
    _p(321, '收款人管理', 'POST', '/api/beneficiaries', '转账汇款', '添加常用收款人',
       ['name', 'account_no', 'bank_name', 'bank_code'], ['beneficiary_id']),
    _p(322, '收款人列表', 'GET', '/api/beneficiaries', '转账汇款', '查询常用收款人',
       ['page'], ['beneficiaries']),
    _p(323, '行内转账', 'POST', '/api/transfers/internal', '转账汇款', '本行账户间转账',
       ['from_account', 'to_account', 'amount', 'remark'], ['transfer_id']),
    _p(324, '跨行转账', 'POST', '/api/transfers/cross-bank', '转账汇款', '跨行转账',
       ['from_account', 'to_account', 'to_bank', 'amount', 'remark'], ['transfer_id']),
    _p(325, '跨境汇款', 'POST', '/api/transfers/remittance', '转账汇款', '跨境汇款',
       ['from_account', 'to_account', 'to_bank', 'swift_code', 'amount', 'currency', 'purpose'],
       ['remittance_id', 'status']),
    _p(326, '汇款状态查询', 'GET', '/api/transfers/remittance/{remittance_id}', '转账汇款', '查询汇款进度',
       ['remittance_id'], ['status', 'progress']),
    # 交易管理 (6)
    _p(327, '交易流水查询', 'GET', '/api/accounts/{account_no}/transactions', '交易管理', '查询交易流水',
       ['account_no', 'date_from', 'date_to', 'type', 'page'], ['transactions', 'total']),
    _p(328, '交易详情', 'GET', '/api/transactions/{transaction_id}', '交易管理', '查询交易详情',
       ['transaction_id'], ['transaction_id', 'type', 'amount', 'status', 'time', 'counterparty']),
    _p(329, '交易撤销', 'POST', '/api/transactions/{transaction_id}/reverse', '交易管理', '撤销交易',
       ['transaction_id', 'reason'], ['reverse_id', 'status']),
    _p(330, '冲正', 'POST', '/api/transactions/{transaction_id}/correct', '交易管理', '冲正交易',
       ['transaction_id', 'reason', 'operator_id'], ['correct_id']),
    _p(331, '交易统计', 'GET', '/api/transactions/stats', '交易管理', '交易量统计',
       ['date_from', 'date_to', 'type'], ['count', 'total_amount', 'by_type']),
    _p(332, '电子回单', 'GET', '/api/transactions/{transaction_id}/receipt', '交易管理', '下载电子回单',
       ['transaction_id'], ['receipt_url']),
    # 贷款管理 (10)
    _p(333, '贷款申请', 'POST', '/api/loans/apply', '贷款管理', '提交贷款申请',
       ['customer_id', 'loan_type', 'amount', 'term_months', 'purpose'], ['loan_id', 'status']),
    _p(334, '贷款审批', 'POST', '/api/loans/{loan_id}/approve', '贷款管理', '审批贷款申请',
       ['loan_id', 'action', 'approved_amount', 'comment'], ['loan_id', 'status']),
    _p(335, '贷款还款', 'POST', '/api/loans/{loan_id}/repay', '贷款管理', '贷款还款',
       ['loan_id', 'amount', 'repayment_type'], ['repayment_id', 'remaining_principal']),
    _p(336, '贷款详情', 'GET', '/api/loans/{loan_id}', '贷款管理', '查询贷款详情',
       ['loan_id'], ['loan_id', 'status', 'amount', 'rate', 'term', 'remaining']),
    _p(337, '贷款列表', 'GET', '/api/loans', '贷款管理', '查询贷款列表',
       ['customer_id', 'status', 'page'], ['loans', 'total']),
    _p(338, '提前还款', 'POST', '/api/loans/{loan_id}/prepay', '贷款管理', '提前还清贷款',
       ['loan_id', 'amount'], ['prepayment_id', 'penalty', 'remaining']),
    _p(339, '贷款产品列表', 'GET', '/api/loan/products', '贷款管理', '查询贷款产品',
       ['loan_type'], ['products']),
    _p(340, '还款计划查询', 'GET', '/api/loans/{loan_id}/schedule', '贷款管理', '查询还款计划',
       ['loan_id'], ['schedule']),
    _p(341, '逾期管理', 'POST', '/api/loans/{loan_id}/overdue', '贷款管理', '标记贷款逾期',
       ['loan_id', 'overdue_date', 'penalty_amount'], []),
    _p(342, '贷款展期', 'POST', '/api/loans/{loan_id}/extend', '贷款管理', '申请贷款展期',
       ['loan_id', 'extend_months', 'reason'], ['extend_id', 'status']),
    # 理财管理 (10)
    _p(343, '理财产品查询', 'GET', '/api/wealth/products', '理财管理', '查询理财产品',
       ['risk_level', 'term_type', 'min_amount'], ['products', 'total']),
    _p(344, '理财产品详情', 'GET', '/api/wealth/products/{product_id}', '理财管理', '查询理财产品详情',
       ['product_id'], ['product_id', 'name', 'rate', 'risk_level', 'term', 'min_amount']),
    _p(345, '购买理财', 'POST', '/api/wealth/purchase', '理财管理', '购买理财产品',
       ['product_id', 'amount', 'account_no'], ['order_id', 'status']),
    _p(346, '赎回理财', 'POST', '/api/wealth/redeem', '理财管理', '赎回理财产品',
       ['order_id', 'amount'], ['redeem_id', 'status']),
    _p(347, '理财持仓查询', 'GET', '/api/wealth/holdings', '理财管理', '查询理财持仓',
       ['customer_id', 'status'], ['holdings']),
    _p(348, '理财收益查询', 'GET', '/api/wealth/earnings', '理财管理', '查询理财收益',
       ['customer_id', 'date_from', 'date_to'], ['total_earnings', 'by_product']),
    _p(349, '基金查询', 'GET', '/api/funds', '理财管理', '查询基金列表',
       ['type', 'risk_level', 'page'], ['funds', 'total']),
    _p(350, '基金购买', 'POST', '/api/funds/purchase', '理财管理', '购买基金',
       ['fund_code', 'amount', 'account_no'], ['order_id']),
    _p(351, '基金赎回', 'POST', '/api/funds/redeem', '理财管理', '赎回基金',
       ['order_id', 'shares'], ['redeem_id']),
    _p(352, '基金净值查询', 'GET', '/api/funds/{fund_code}/nav', '理财管理', '查询基金净值',
       ['fund_code', 'date'], ['nav', 'accumulated_nav']),
    # 风控管理 (8)
    _p(353, '风控评估', 'POST', '/api/risk/assess', '风控管理', '对客户或交易风险评估',
       ['customer_id', 'assess_type', 'params'], ['risk_level', 'score', 'factors']),
    _p(354, '黑名单查询', 'GET', '/api/risk/blacklist', '风控管理', '查询黑名单',
       ['keyword', 'type'], ['matches']),
    _p(355, '黑名单新增', 'POST', '/api/risk/blacklist', '风控管理', '添加黑名单',
       ['name', 'type', 'id_no', 'reason'], ['blacklist_id']),
    _p(356, '黑名单移除', 'DELETE', '/api/risk/blacklist/{id}', '风控管理', '移除黑名单',
       ['id'], []),
    _p(357, '反洗钱监测', 'POST', '/api/risk/aml/check', '风控管理', '反洗钱监测',
       ['customer_id', 'transaction_id', 'amount'], ['aml_result', 'alert_level']),
    _p(358, '可疑交易上报', 'POST', '/api/risk/aml/report', '风控管理', '上报可疑交易',
       ['transaction_id', 'suspect_type', 'description'], ['report_id']),
    _p(359, '风控规则配置', 'GET', '/api/risk/rules', '风控管理', '查询风控规则',
       ['type', 'status'], ['rules']),
    _p(360, '风控规则修改', 'PUT', '/api/risk/rules/{rule_id}', '风控管理', '修改风控规则',
       ['rule_id', 'conditions', 'actions'], []),
]

FINANCE_CASES = [
    # 账户
    ('开户', 301, '基础'), ('开立账户', 301, '同义'), ('开卡', 301, '口语'),
    ('账户查询', 302, '基础'), ('查账户', 302, '口语'), ('查余额', 307, '口语'),
    ('销户', 303, '基础'), ('注销账户', 303, '同义'), ('关户', 303, '口语'),
    ('账户冻结', 304, '基础'), ('冻结账户', 304, '口语'), ('冻卡', 304, '术语'),
    ('账户解冻', 305, '基础'), ('解冻', 305, '口语'), ('解冻账户', 305, '口语'),
    ('账户列表', 306, '基础'), ('查所有账户', 306, '口语'),
    ('余额查询', 307, '口语'), ('看余额', 307, '口语'),
    ('查询限额', 308, '口语'), ('看额度', 308, '口语'),
    ('修改限额', 309, '口语'), ('调限额', 309, '口语'),
    ('重置密码', 310, '口语'), ('改密码', 310, '口语'),
    # 存取款
    ('存款', 311, '基础'), ('存钱', 311, '口语'),
    ('取款', 312, '基础'), ('取钱', 312, '口语'),
    ('存款产品', 313, '口语'), ('查存款类型', 313, '口语'),
    ('定期存款开户', 314, '基础'), ('存定期', 314, '口语'),
    ('定期存款支取', 315, '基础'), ('提前取定期', 315, '口语'),
    ('通知存款', 316, '基础'), ('开通知存款', 316, '口语'),
    ('大额存单', 317, '口语'), ('查存单', 317, '口语'),
    ('利息计算', 318, '基础'), ('算利息', 318, '口语'),
    # 转账
    ('转账', 319, '基础'), ('汇款', 319, '同义'), ('打钱', 319, '口语'),
    ('转账记录', 320, '口语'), ('查转账', 320, '口语'),
    ('添加收款人', 321, '口语'), ('新建收款人', 321, '口语'),
    ('收款人列表', 322, '基础'), ('看收款人', 322, '口语'),
    ('行内转账', 323, '基础'), ('本行转账', 323, '同义'),
    ('跨行转账', 324, '基础'), ('转他行', 324, '口语'),
    ('跨境汇款', 325, '基础'), ('国际汇款', 325, '同义'), ('海外打钱', 325, '口语'),
    ('汇款状态', 326, '口语'), ('汇款到了吗', 326, '问句'),
    # 交易
    ('交易流水查询', 327, '基础'), ('查流水', 327, '口语'), ('看交易记录', 327, '口语'),
    ('交易详情', 328, '基础'), ('看交易明细', 328, '口语'),
    ('交易撤销', 329, '基础'), ('撤销交易', 329, '口语'), ('撤交易', 329, '口语'),
    ('冲正', 330, '基础'), ('冲正交易', 330, '口语'),
    ('交易统计', 331, '基础'), ('看交易量', 331, '口语'),
    ('电子回单', 332, '基础'), ('下载回单', 332, '口语'),
    # 贷款
    ('贷款申请', 333, '基础'), ('申请贷款', 333, '口语'), ('借钱', 333, '口语'),
    ('贷款审批', 334, '基础'), ('审批贷款', 334, '口语'),
    ('贷款还款', 335, '基础'), ('还贷款', 335, '口语'), ('还款', 335, '口语'),
    ('贷款详情', 336, '基础'), ('查贷款信息', 336, '口语'),
    ('贷款列表', 337, '基础'), ('查贷款', 337, '口语'),
    ('提前还款', 338, '基础'), ('提前还清', 338, '口语'),
    ('贷款产品', 339, '口语'), ('有什么贷款', 339, '问句'),
    ('还款计划', 340, '口语'), ('看还款计划', 340, '口语'),
    ('逾期管理', 341, '基础'), ('标记逾期', 341, '口语'),
    ('贷款展期', 342, '基础'), ('展期', 342, '术语'),
    # 理财
    ('理财产品查询', 343, '基础'), ('查理财', 343, '口语'), ('有什么理财', 343, '问句'),
    ('理财产品详情', 344, '基础'), ('看理财详情', 344, '口语'),
    ('购买理财', 345, '基础'), ('买理财', 345, '口语'),
    ('赎回理财', 346, '基础'), ('理财赎回', 346, '口语'),
    ('理财持仓', 347, '口语'), ('看我买了什么理财', 347, '问句'),
    ('理财收益', 348, '口语'), ('赚了多少', 348, '问句'),
    ('基金查询', 349, '基础'), ('查基金', 349, '口语'),
    ('基金购买', 350, '基础'), ('买基金', 350, '口语'),
    ('基金赎回', 351, '基础'), ('卖基金', 351, '口语'),
    ('基金净值', 352, '口语'), ('看基金价格', 352, '口语'),
    # 风控
    ('风控评估', 353, '基础'), ('风险评估', 353, '同义'),
    ('黑名单查询', 354, '基础'), ('查黑名单', 354, '口语'),
    ('加黑名单', 355, '口语'), ('拉黑', 355, '口语'),
    ('移除黑名单', 356, '基础'), ('解除黑名单', 356, '口语'),
    ('反洗钱', 357, '口语'), ('AML监测', 357, '术语'),
    ('可疑交易上报', 358, '基础'), ('报可疑', 358, '口语'),
    ('风控规则', 359, '口语'), ('查风控规则', 359, '口语'),
    ('修改风控规则', 360, '基础'), ('改规则', 360, '口语'),
]

# ═══════════════════════════════════════════════════════════════
#  支付行业 60 接口
# ═══════════════════════════════════════════════════════════════
PAYMENT = [
    # 收单管理 (10)
    _p(401, '创建收单', 'POST', '/api/acquiring/orders', '收单管理', '商户创建收单交易',
       ['merchant_id', 'amount', 'currency', 'pay_method', 'notify_url', 'subject'],
       ['trade_no', 'pay_url', 'qr_code']),
    _p(402, '查询收单状态', 'GET', '/api/acquiring/orders/{trade_no}', '收单管理', '查询收单支付状态',
       ['trade_no'], ['trade_no', 'status', 'pay_time', 'amount']),
    _p(403, '关闭收单', 'POST', '/api/acquiring/orders/{trade_no}/close', '收单管理', '关闭未支付收单',
       ['trade_no'], ['trade_no', 'status']),
    _p(404, '收单回调通知', 'POST', '/api/acquiring/notify', '收单管理', '支付结果异步通知',
       ['trade_no', 'status', 'amount', 'sign', 'gmt_payment'], []),
    _p(405, '收单列表', 'GET', '/api/acquiring/orders', '收单管理', '查询收单交易列表',
       ['merchant_id', 'status', 'date_from', 'date_to', 'page'], ['orders', 'total']),
    _p(406, '收单详情', 'GET', '/api/acquiring/orders/{trade_no}/detail', '收单管理', '查询收单交易详情',
       ['trade_no'], ['trade_no', 'merchant_id', 'amount', 'status', 'pay_method', 'pay_time']),
    _p(407, '收单撤销', 'POST', '/api/acquiring/orders/{trade_no}/reverse', '收单管理', '撤销收单交易',
       ['trade_no', 'reason'], ['trade_no', 'status']),
    _p(408, '刮刮卡支付', 'POST', '/api/acquiring/scratch-card', '收单管理', '刮刮卡支付方式',
       ['card_no', 'card_password', 'trade_no'], ['status', 'amount']),
    _p(409, '预授权', 'POST', '/api/acquiring/pre-auth', '收单管理', '发起预授权冻结',
       ['merchant_id', 'amount', 'currency', 'pay_method'], ['auth_no', 'status']),
    _p(410, '预授权完成', 'POST', '/api/acquiring/pre-auth/{auth_no}/capture', '收单管理', '预授权扣款完成',
       ['auth_no', 'capture_amount'], ['trade_no', 'status']),
    # 退款管理 (8)
    _p(411, '申请退款', 'POST', '/api/refunds', '退款管理', '对已支付交易申请退款',
       ['trade_no', 'refund_amount', 'reason', 'out_request_no'], ['refund_no', 'status']),
    _p(412, '查询退款状态', 'GET', '/api/refunds/{refund_no}', '退款管理', '查询退款进度',
       ['refund_no'], ['refund_no', 'status', 'refund_amount', 'success_time']),
    _p(413, '退款回调', 'POST', '/api/refunds/notify', '退款管理', '退款结果异步通知',
       ['refund_no', 'status', 'refund_amount', 'sign'], []),
    _p(414, '退款列表', 'GET', '/api/refunds', '退款管理', '查询退款记录列表',
       ['merchant_id', 'trade_no', 'status', 'date_from', 'date_to', 'page'], ['refunds', 'total']),
    _p(415, '退款详情', 'GET', '/api/refunds/{refund_no}/detail', '退款管理', '查询退款详情',
       ['refund_no'], ['refund_no', 'trade_no', 'amount', 'status', 'reason', 'create_time']),
    _p(416, '批量退款', 'POST', '/api/refunds/batch', '退款管理', '批量申请退款',
       ['refunds'], ['results', 'success_count', 'fail_count']),
    _p(417, '退款拒绝', 'POST', '/api/refunds/{refund_no}/reject', '退款管理', '拒绝退款',
       ['refund_no', 'reason'], ['refund_no', 'status']),
    _p(418, '退款撤销', 'POST', '/api/refunds/{refund_no}/cancel', '退款管理', '撤销退款申请',
       ['refund_no'], ['refund_no', 'status']),
    # 商户管理 (10)
    _p(419, '商户入驻', 'POST', '/api/merchants/onboard', '商户管理', '商户入驻申请',
       ['merchant_name', 'contact', 'business_type', 'license_no', 'bank_account'],
       ['merchant_id', 'status']),
    _p(420, '商户信息查询', 'GET', '/api/merchants/{merchant_id}', '商户管理', '查询商户详情',
       ['merchant_id'], ['merchant_id', 'name', 'status', 'settlement_account', 'rate']),
    _p(421, '商户信息变更', 'PUT', '/api/merchants/{merchant_id}', '商户管理', '修改商户信息',
       ['merchant_id', 'contact', 'phone', 'address'], []),
    _p(422, '商户列表', 'GET', '/api/merchants', '商户管理', '查询商户列表',
       ['page', 'page_size', 'status', 'business_type'], ['merchants', 'total']),
    _p(423, '商户注销', 'POST', '/api/merchants/{merchant_id}/offboard', '商户管理', '商户注销',
       ['merchant_id', 'reason'], ['merchant_id', 'status']),
    _p(424, '商户费率查询', 'GET', '/api/merchants/{merchant_id}/rates', '商户管理', '查询商户费率',
       ['merchant_id'], ['rates']),
    _p(425, '商户费率修改', 'PUT', '/api/merchants/{merchant_id}/rates', '商户管理', '修改商户费率',
       ['merchant_id', 'pay_method', 'rate'], []),
    _p(426, '商户限额查询', 'GET', '/api/merchants/{merchant_id}/limits', '商户管理', '查询商户限额',
       ['merchant_id'], ['daily_limit', 'single_limit']),
    _p(427, '商户冻结', 'POST', '/api/merchants/{merchant_id}/freeze', '商户管理', '冻结商户',
       ['merchant_id', 'reason'], ['merchant_id', 'status']),
    _p(428, '商户解冻', 'POST', '/api/merchants/{merchant_id}/unfreeze', '商户管理', '解冻商户',
       ['merchant_id'], ['merchant_id', 'status']),
    # 结算管理 (8)
    _p(429, '发起结算', 'POST', '/api/settlements', '结算管理', '发起商户结算',
       ['merchant_id', 'settlement_type', 'amount'], ['settlement_id', 'status']),
    _p(430, '结算记录查询', 'GET', '/api/settlements', '结算管理', '查询结算记录',
       ['merchant_id', 'date_from', 'date_to', 'page'], ['settlements', 'total']),
    _p(431, '结算详情', 'GET', '/api/settlements/{settlement_id}', '结算管理', '查询结算详情',
       ['settlement_id'], ['settlement_id', 'merchant_id', 'amount', 'status', 'bank_info']),
    _p(432, '结算汇总', 'GET', '/api/settlements/summary', '结算管理', '结算汇总统计',
       ['merchant_id', 'period'], ['total_amount', 'total_count', 'by_status']),
    _p(433, '结算打款', 'POST', '/api/settlements/{settlement_id}/pay', '结算管理', '结算打款',
       ['settlement_id', 'pay_method'], ['settlement_id', 'status']),
    _p(434, '结算失败重试', 'POST', '/api/settlements/{settlement_id}/retry', '结算管理', '结算打款失败重试',
       ['settlement_id'], ['settlement_id', 'status']),
    _p(435, 'T+1结算规则', 'GET', '/api/settlements/rules', '结算管理', '查询结算规则',
       ['merchant_id'], ['rules']),
    _p(436, '结算调整', 'POST', '/api/settlements/{settlement_id}/adjust', '结算管理', '结算金额调整',
       ['settlement_id', 'adjust_amount', 'reason'], ['settlement_id', 'adjusted_amount']),
    # 对账管理 (6)
    _p(437, '对账文件下载', 'GET', '/api/reconciliation/files/{date}', '对账管理', '下载对账文件',
       ['date'], ['file_url', 'record_count']),
    _p(438, '对账结果查询', 'GET', '/api/reconciliation/results', '对账管理', '查询对账结果',
       ['date', 'status'], ['results']),
    _p(439, '差错处理', 'POST', '/api/reconciliation/discrepancies/{id}/handle', '对账管理', '处理对账差错',
       ['id', 'action', 'amount'], ['id', 'status']),
    _p(440, '长款处理', 'POST', '/api/reconciliation/overages/{id}/handle', '对账管理', '处理长款',
       ['id', 'action', 'target_merchant'], ['id', 'status']),
    _p(441, '短款处理', 'POST', '/api/reconciliation/shortages/{id}/handle', '对账管理', '处理短款',
       ['id', 'action', 'source_merchant'], ['id', 'status']),
    _p(442, '对账汇总报表', 'GET', '/api/reconciliation/summary', '对账管理', '对账汇总报表',
       ['date_from', 'date_to'], ['summary']),
    # 风控管理 (6)
    _p(443, '交易风控评估', 'POST', '/api/risk/assess-transaction', '风控管理', '评估交易风险',
       ['trade_no', 'merchant_id', 'amount', 'pay_method', 'ip', 'device_id'],
       ['risk_level', 'score', 'suggestion']),
    _p(444, '风控规则查询', 'GET', '/api/risk/rules', '风控管理', '查询风控规则',
       ['type', 'status'], ['rules']),
    _p(445, '风控规则新增', 'POST', '/api/risk/rules', '风控管理', '新增风控规则',
       ['name', 'type', 'conditions', 'actions'], ['rule_id']),
    _p(446, '风控规则修改', 'PUT', '/api/risk/rules/{rule_id}', '风控管理', '修改风控规则',
       ['rule_id', 'conditions', 'actions'], []),
    _p(447, '风控事件列表', 'GET', '/api/risk/events', '风控管理', '查询风控事件',
       ['date_from', 'date_to', 'level', 'status'], ['events', 'total']),
    _p(448, '风控事件处理', 'POST', '/api/risk/events/{event_id}/handle', '风控管理', '处理风控事件',
       ['event_id', 'action', 'comment'], ['event_id', 'status']),
    # 渠道路由 (6)
    _p(449, '支付路由查询', 'POST', '/api/routing/query', '渠道路由', '查询最优支付通道',
       ['pay_method', 'amount', 'merchant_id', 'scene'], ['channel_id', 'channel_name', 'fee_rate']),
    _p(450, '渠道列表', 'GET', '/api/channels', '渠道路由', '查询支付渠道列表',
       ['status', 'pay_method'], ['channels']),
    _p(451, '渠道详情', 'GET', '/api/channels/{channel_id}', '渠道路由', '查询渠道详情',
       ['channel_id'], ['channel_id', 'name', 'status', 'fee_rate', 'limits']),
    _p(452, '渠道开通', 'POST', '/api/channels/{channel_id}/enable', '渠道路由', '开通支付渠道',
       ['channel_id', 'merchant_id'], ['channel_id', 'status']),
    _p(453, '渠道关闭', 'POST', '/api/channels/{channel_id}/disable', '渠道路由', '关闭支付渠道',
       ['channel_id', 'merchant_id', 'reason'], ['channel_id', 'status']),
    _p(454, '渠道路由规则', 'GET', '/api/routing/rules', '渠道路由', '查询路由规则',
       ['pay_method', 'scene'], ['rules']),
    # 账务 (6)
    _p(455, '调账', 'POST', '/api/adjustments', '账务管理', '发起账务调整',
       ['type', 'trade_no', 'amount', 'reason'], ['adjustment_id', 'status']),
    _p(456, '调账详情', 'GET', '/api/adjustments/{adjustment_id}', '账务管理', '查询调账详情',
       ['adjustment_id'], ['adjustment_id', 'type', 'amount', 'status', 'reason']),
    _p(457, '调账列表', 'GET', '/api/adjustments', '账务管理', '查询调账记录',
       ['type', 'status', 'date_from', 'date_to', 'page'], ['adjustments', 'total']),
    _p(458, '试算', 'POST', '/api/trial-balance', '账务管理', '账务试算平衡',
       ['date', 'account_type'], ['debit_total', 'credit_total', 'balanced']),
    _p(459, '账户流水', 'GET', '/api/ledger/transactions', '账务管理', '查询账务流水',
       ['account_no', 'date_from', 'date_to', 'page'], ['transactions', 'total']),
    _p(460, '日终结账', 'POST', '/api/ledger/eod', '账务管理', '日终结账处理',
       ['date'], ['eod_id', 'status']),
]

PAYMENT_CASES = [
    # 收单
    ('创建收单', 401, '基础'), ('收款', 401, '口语'), ('商户收款', 401, '口语'), ('发起支付', 401, '口语'),
    ('查询收单状态', 402, '基础'), ('查支付状态', 402, '口语'), ('付款成功了吗', 402, '问句'),
    ('关闭收单', 403, '基础'), ('取消支付', 403, '口语'), ('关单', 403, '术语'),
    ('收单回调通知', 404, '基础'), ('回调', 404, '口语'), ('支付通知', 404, '口语'),
    ('收单列表', 405, '基础'), ('查交易', 405, '口语'),
    ('收单详情', 406, '基础'), ('看交易详情', 406, '口语'),
    ('收单撤销', 407, '基础'), ('撤销交易', 407, '口语'),
    ('刮刮卡支付', 408, '基础'), ('刮刮卡', 408, '口语'),
    ('预授权', 409, '基础'), ('冻结资金', 409, '口语'), ('授权', 409, '口语'),
    ('预授权完成', 410, '基础'), ('完成授权扣款', 410, '口语'),
    # 退款
    ('申请退款', 411, '基础'), ('退款', 411, '口语'), ('退钱', 411, '口语'),
    ('查询退款状态', 412, '基础'), ('退款到账了吗', 412, '问句'), ('看退款进度', 412, '口语'),
    ('退款回调', 413, '基础'), ('退款通知', 413, '口语'),
    ('退款列表', 414, '基础'), ('查退款记录', 414, '口语'),
    ('退款详情', 415, '基础'), ('看退款信息', 415, '口语'),
    ('批量退款', 416, '基础'), ('批量退', 416, '口语'),
    ('退款拒绝', 417, '基础'), ('拒绝退款', 417, '口语'),
    ('退款撤销', 418, '基础'), ('撤销退款', 418, '口语'),
    # 商户
    ('商户入驻', 419, '基础'), ('入驻商户', 419, '倒序'), ('接入新商户', 419, '口语'), ('开商户', 419, '口语'),
    ('商户信息查询', 420, '基础'), ('查商户', 420, '口语'),
    ('商户信息变更', 421, '基础'), ('改商户信息', 421, '口语'),
    ('商户列表', 422, '基础'), ('查所有商户', 422, '口语'),
    ('商户注销', 423, '基础'), ('注销商户', 423, '口语'),
    ('商户费率查询', 424, '基础'), ('查费率', 424, '口语'), ('看扣率', 424, '术语'),
    ('商户费率修改', 425, '基础'), ('改费率', 425, '口语'),
    ('商户限额查询', 426, '基础'), ('看限额', 426, '口语'),
    ('商户冻结', 427, '基础'), ('冻结商户', 427, '口语'),
    ('商户解冻', 428, '基础'), ('解冻商户', 428, '口语'),
    # 结算
    ('发起结算', 429, '基础'), ('结算', 429, '口语'), ('商户提现', 429, '口语'),
    ('结算记录查询', 430, '基础'), ('查结算记录', 430, '口语'),
    ('结算详情', 431, '基础'), ('看结算信息', 431, '口语'),
    ('结算汇总', 432, '基础'), ('看结算统计', 432, '口语'),
    ('结算打款', 433, '基础'), ('打款', 433, '口语'),
    ('结算失败重试', 434, '基础'), ('重试打款', 434, '口语'),
    ('结算规则', 435, '口语'), ('看结算配置', 435, '口语'),
    ('结算调整', 436, '基础'), ('调整结算金额', 436, '口语'),
    # 对账
    ('对账文件下载', 437, '基础'), ('下载对账文件', 437, '口语'), ('下对账单', 437, '口语'),
    ('对账结果查询', 438, '基础'), ('查对账结果', 438, '口语'),
    ('差错处理', 439, '基础'), ('处理差错', 439, '口语'),
    ('长款处理', 440, '基础'), ('处理长款', 440, '口语'),
    ('短款处理', 441, '基础'), ('处理短款', 441, '口语'),
    ('对账汇总报表', 442, '基础'), ('看对账报表', 442, '口语'),
    # 风控
    ('交易风控评估', 443, '基础'), ('评估风险', 443, '口语'),
    ('风控规则查询', 444, '基础'), ('查风控', 444, '口语'),
    ('风控规则新增', 445, '基础'), ('加风控规则', 445, '口语'),
    ('风控规则修改', 446, '基础'), ('改风控', 446, '口语'),
    ('风控事件列表', 447, '基础'), ('查风控事件', 447, '口语'),
    ('风控事件处理', 448, '基础'), ('处理风控', 448, '口语'),
    # 渠道
    ('支付路由查询', 449, '基础'), ('查支付通道', 449, '口语'), ('路由', 449, '术语'),
    ('渠道列表', 450, '基础'), ('查渠道', 450, '口语'),
    ('渠道详情', 451, '基础'), ('看渠道信息', 451, '口语'),
    ('渠道开通', 452, '基础'), ('开通渠道', 452, '口语'),
    ('渠道关闭', 453, '基础'), ('关渠道', 453, '口语'),
    ('渠道路由规则', 454, '基础'), ('看路由规则', 454, '口语'),
    # 账务
    ('调账', 455, '基础'), ('差错调整', 455, '术语'),
    ('调账详情', 456, '基础'), ('看调账信息', 456, '口语'),
    ('调账列表', 457, '基础'), ('查调账记录', 457, '口语'),
    ('试算', 458, '基础'), ('账务试算', 458, '口语'),
    ('账户流水', 459, '基础'), ('查流水', 459, '口语'),
    ('日终结账', 460, '基础'), ('结账', 460, '口语'),
]

# ═══════════════════════════════════════════════════════════════
#  汇总
# ═══════════════════════════════════════════════════════════════

INDUSTRIES = [
    ('电商', ECOMMERCE, ECOMMERCE_CASES),
    ('物流', LOGISTICS, LOGISTICS_CASES),
    ('ERP', ERP, ERP_CASES),
    ('金融', FINANCE, FINANCE_CASES),
    ('支付', PAYMENT, PAYMENT_CASES),
]

TOTAL_INTERFACES = len(ECOMMERCE) + len(LOGISTICS) + len(ERP) + len(FINANCE) + len(PAYMENT)
TOTAL_CASES = (len(ECOMMERCE_CASES) + len(LOGISTICS_CASES) + len(ERP_CASES)
               + len(FINANCE_CASES) + len(PAYMENT_CASES))